version: '3.8'
services:
  ai_worker:
    build:
      context: ..        
      dockerfile: chat_service/Dockerfile 
    environment:
      - HF_TOKEN=${HF_TOKEN}
    env_file: .env
    restart: always
    deploy:
      replicas: 5